######################################################################
#                     --  configuration switch --                    #
######################################################################
######################################################################
#                          -- server --                              #
######################################################################
server:
  port: 8996
#  max-http-header-size: 1048567
#    tomcat:
#      max-http-post-size: 1048567
  servlet:
    # 应用的访问路径
    context-path: /job

######################################################################
#                          -- spring --                              #
######################################################################
spring:
  profiles:
    active: dev

    ######################################################################
    #                          -- tomcat --                              #
    #####################################################################
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8

  ######################################################################
  #                            -- jpa --                               #
  ######################################################################
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

######################################################################
#                       -- mybatis-plus --                           #
######################################################################
mybatis-plus:
  mapper-locations: classpath*:com/ll/mapper**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

  ############################ --  jackson -- ############################
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

######################################################################
#                           -- item --                               #
######################################################################
ll:
  name: lessons learned
  # 版本
  version: 1.0.0
  # 版权年份
  year: 2020
  # 成员
  member: ChenYongbin、MengXiaodong、ChenYongkun

######################################################################
#                       -- final-value --                           #
######################################################################
log-path: d:/logs
app-dir : job
log-level: DEBUG

security-fig:
  swagger-url:  /doc