spring:

  application:
    name: ll-job

  ## mysql配置
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: root
    password:
    hikari:
      schema: classpath:sql

eureka:
  client:
    enabled: true
    registry-fetch-interval-seconds: 10
    service-url:
      # default-zone 不可以（目前只能这么写）
      defaultZone:  http://127.0.0.1:8080/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15